server:
  AppVersion: 1.0.0
  Port: :8080
  ReadTimeout: 10
  WriteTimeout: 10

postgres:
  PostgresqlHost: db-service
  PostgresqlPort: 5432
  PostgresqlUser: program
  PostgresqlPassword: test
  PostgresqlDbname: loyalties
