apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  namespace: dips
data:
  listen-address: 0.0.0.0:8080
  bonus-service-address: http://bonus.rsoi.svc.cluster.local:8050
  flight-service-address: http://flight.rsoi.svc.cluster.local:8060
  ticket-service-address: http://ticket.rsoi.svc.cluster.local:8070
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: dips
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: efremovrd/bmstu-dips-lab4-gateway-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: LISTEN_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: gateway-config
              key: listen-address
        - name: BONUS_SERVICE_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: gateway-config
              key: bonus-service-address
        - name: FLIGHT_SERVICE_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: gateway-config
              key: flight-service-address
        - name: TICKET_SERVICE_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: gateway-config
              key: ticket-service-address
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: dips
  labels:
    app: gateway
spec:
  selector:
    app: gateway
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30000